name: Deploy to Github Pages

on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: "git clone"
              run: |
                git clone --depth 1 --branch "${GITHUB_REF_NAME}" \
                "https://github.com/${GITHUB_REPOSITORY}.git" .
            - name: "setup Github Pages"
              uses: actions/configure-pages@v6
        
            - name: "upload artifact as Github Pages"
              uses: actions/upload-pages-artifact@v5
              with:
                path: '.'
            
            - name: "deploy to GitHub Pages"
              id: "deployment"
              uses: actions/deploy-pages@v5
